xcodeproj '/Users/joshuaherrera/Desktop/mALS test/mALS test.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'mALS test' do
use_frameworks!

pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
pod 'OpenSSL-Universal', '~> 1.0.1.l'
pod 'MSWeakTimer', '~> 1.1.0'
pod 'CocoaAsyncSocket'  



end

target 'mALS testTests' do

end

